const int = 2;
console.log(int);
let number = 1;
console.log(number);
let String = "Rede cidadã";
console.log(String);
let double = 3.141516;
console.log(double);
let boolean = true;
console.log(boolean);
let array = [1,2,3,4,5,6];
console.log(array);
let mixedarray = [1, 3.141516, "String para demonstração", false];
console.log(mixedarray);
let matrices = [[1,2,3],[1,2,3],[1,2,3]];
console.log(matrices);
